development:
  adapter: mysql2
  encoding: utf8
  username: root
  password: qweqwe
  database: bitcoin_dev

test:
  adapter: mysql2
  encoding: utf8
  username: root
  password: qweqwe
  database: bitcoin_test
